config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :home
  resources :tests do
    get 'close', on: :collection
  end
  resources :questions
  resources :users do
    get 'details', on: :collection
    get 'score', on: :member
  end
  resources :answers
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :question
  belongs_to :user

  field :answer_ids, type: Array
  validates_presence_of :answer_ids
  field :time_taken, type: Fixnum
end

app/models/option.rb
class Option
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :question
  belongs_to :answerer, class_name: 'Question', inverse_of: :answers

  field :opt_value, type: String
  validates_presence_of :opt_value
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :options
  has_many :answers, class_name: 'Option', inverse_of: :answerer

  field :content, type: String
  validates_presence_of :content

  field :option_type, type: String
  validates_presence_of :option_type

  field :seconds, type: Fixnum
  validates_presence_of :seconds
end

app/models/test.rb
class Test
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :questions
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :answers

  field :name, type: String
  validates_presence_of :name

  field :email, type: String, default: ''
  validates :email, presence: true, allow_blank: false
  validates :email, format: { with: /\A[a-zA-Z0-9.!#$%&'\*\+\/=\?\^\_\`\{\|\}\~-]{1,64}@((?:[-a-z0-9]+\.)+[a-z]{2,})\s*\z/i, message: "Please provide valid email" }
  validates_uniqueness_of    :email

  field :phone_number
  validates_presence_of :phone_number
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question_id = params[:question_id]
    answers = params[:answers]
    time_taken = params[:time_taken]
    question = Question.find(question_id)
    time_taken_for_question = time_taken_by_user(question, time_taken)
    answer = Answer.new
    answer.question = question
    answer.user_id = session[:current_user]['_id']['$oid']
    answer.answer_ids = answers.split(',') if answers.present?
    answer.time_taken = time_taken_for_question
    answer.save
  end

  private

  def time_taken_by_user(question, time_taken)
    seconds = question.seconds
    time_taken_mins = time_taken.split(':')[0]
    time_taken_secs = time_taken.split(':')[1]
    total_secs = (time_taken_mins.to_i*60) + time_taken_secs.to_i
    seconds - total_secs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    redirect_to tests_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Questions

  def index
    if session[:current_user].blank?
      redirect_to users_path
    else
      qns = Option.where(:answerer_id.ne => nil).pluck(:question_id).uniq
      @questions = Question.where(id: { '$in': qns }).order_by(created_at: 'desc')
    end
  end

  def create
    question_content = params[:question_content]
    option_type = params[:option_type]
    minutes = params[:minutes].to_i.minutes
    option_values = params[:option_value]
    @errors, @questions = create_question(minutes, option_type, option_values, question_content)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  include Scores


  def index
    qns = Option.where(:answerer_id.ne => nil).pluck(:question_id).uniq
    @questions = Question.where(id: { '$in': qns }).order_by(created_at: 'desc')
    session.delete(:current_user)
  end

  def close
    user_id = session[:current_user]['_id']['$oid']
    @user, @questions, @correct_ans, @user_attempted_questions = get_scores(user_id)
    session.delete(:current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Scores

  def index

  end

  def create
    name = params[:name]
    email = params[:email]
    phone_number = params[:phone_number]
    @user = User.create(name: name, email: email, phone_number: phone_number)
    if @user.valid?
      session[:current_user] = @user
    end
  end

  def details
    @users = User.all
    session.delete(:current_user)
  end

  def score
    user_id = params[:id]
    @user, @questions, @correct_ans, @user_attempted_questions = get_scores(user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/create.js.erb
$('.stepwizard').find('.setup-content').each(function(){
  if ($(this).is(':visible')) {
    var setupCont = $(this);
    var mins = setupCont.find('.question-tag .question-time').val()/60;
    var date = new  Date();
    date.setMinutes(date.getMinutes() + mins);
    $("#timer")
        .countdown(date, function(event) {
          $(this).text(
              event.strftime('%M:%S')
          );
        }).on('finish.countdown', function(){
      setupCont.find('.nextBtn').click();
    });
  }
});

app/views/layouts/_top_nav.html.haml
.top-navigation-content
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{ type: "button", 'data-toggle' => "collapse", 'data-target' => "#bs-example-navbar-collapse-1", 'aria-expanded' => "false" }
          %span.sr-only
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{ href: "#{root_path}" }
          = t('online_test')
      .collapse.navbar-collapse#bs-example-navbar-collapse-1
        - if session[:current_user].blank?
          %ul.nav.navbar-nav.navbar-right#user_info{ style: 'display: flex; align-items: center;' }
            %li
              %a{ href: details_users_path }
                = t('users')
            %li
              %a{ href: users_path }
                = t('take_test')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OnlineTest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
  %body
    .body-container
      #header_container
        = render 'layouts/top_nav'
      #main_container
        .container
          .row
            = yield
      #footer_container

app/views/questions/_answer_the_question.html.haml
.qa-child
  .question-form-container
    .question-tag
      %input{ type: 'text', class: 'form-control input-element question-name', autofocus: 'autofocus', name: 'question_content', placeholder: 'Question here', value: "#{question.present? ? question.content : ''}" }
      %input{ type: 'hidden', class: 'question-id', value: "#{question.present? ? question.id : ''}" }
      %input{ type: 'hidden', class: 'question-time', value: "#{question.present? ? question.seconds : ''}" }
    .options-container
      - if question.present? && question.options.present?
        - question.options.each do |option|
          .option
            - if question.option_type == 'radio'
              %input.option-values{ type: 'radio', name: 'option_value', value: option.id }
            - else
              %input.option-values{ type: 'checkbox', value: option.id, name: 'option_value' }
            %input{ type: 'text', class: 'form-control input-option input-element', name: 'option_value[][op_value]', placeholder: 'option 1', value: "#{option.opt_value.present? ? option.opt_value : '' }" }

app/views/questions/_questions_list.html.haml
.questions-list-content
  %h4 Questions
  - if questions.present?
    - questions.each do |question|
      = render 'tests/child_question', question: question
  - else
    .empty-questions-content
      ******************* Question Not Created At Present ********************

app/views/questions/create.js.erb
$('.question-and-options .question-content .err-content').html("");
<% if @errors.present? %>
  $('.question-and-options .question-content .err-content').html("<%= j render 'shared/errors', errors: @errors %>");
<% else %>
  showFlashMessage('success', 'Question successfully created');
  $(".question-and-options .questions").html("<%= j render 'tests/child_question', question: nil %>");
  $(".question-and-options .questions-list-container").html("<%= j render 'questions/questions_list', questions: @questions %>");
  $('.question-and-options .q-child').each(function(){
    $(this).removeClass('active');
  });
  $('.question-and-options .q-child:last').addClass('active');
<% end %>

app/views/questions/index.html.haml
.user-submission-container
  .questions-list-content
    %h4 Questions
    - if @questions.present?
      .container
        .stepwizard
          .stepwizard-row.setup-panel
            - @questions.each_with_index do |question, index|
              .stepwizard-step
                - if index+1 == 1
                  %a.btn.btn-primary.btn-circle{:href => "#step-#{index+1}", :type => "button"}
                    = index + 1
                - else
                  %a.btn.btn-default.btn-circle{:disabled => "disabled", :href => "#step-#{index+1}", :type => "button"}
                    = index + 1
          %form{:action => "", :method => "post", :role => "form"}
            .timer-container{ style: 'text-align: right;' }
              %button#timer{ name: 'time_taken' }
            - @questions.each_with_index do |question, index|
              %div.row.setup-content{ id: "step-#{index+1}" }
                .col-md-12
                  = render 'questions/answer_the_question', question: question
                  %button.btn.btn-primary.nextBtn.btn-lg.pull-right{:type => "button"} Next

    - else
      .empty-questions-content
        ******************* Question Not Created At Present ********************
  = render 'shared/thankyou_form'

:javascript

  $(function(){
  var timer;
     var navListItems = $('div.setup-panel div a'),
          allWells = $('.setup-content'),
          allNextBtn = $('.nextBtn');

    allWells.hide();

    navListItems.click(function (e) {
        e.preventDefault();
        var $target = $($(this).attr('href')),
                $item = $(this);

        if (!$item.hasClass('disabled')) {
            navListItems.removeClass('btn-primary').addClass('btn-default');
            $item.addClass('btn-primary');
            allWells.hide();
            $target.show();
            $target.find('input:eq(0)').focus();
        }
    });

    allNextBtn.click(function(){
        var curStep = $(this).closest(".setup-content"),
            curStepBtn = curStep.attr("id"),
            nextStepWizard = $('div.setup-panel div a[href="#' + curStepBtn + '"]').parent().next().children("a"),
            curInputs = curStep.find("input[type='text'],input[type='url']"),
            isValid = true;

        $(".form-group").removeClass("has-error");
        for(var i=0; i<curInputs.length; i++){
            if (!curInputs[i].validity.valid){
                isValid = false;
                $(curInputs[i]).closest(".form-group").addClass("has-error");
            }
        }

        if (isValid){
          var questionId = $(this).siblings('.qa-child').find('.question-tag .question-id').val();
          var answers = $(this).siblings('.qa-child').find('.options-container [name=option_value]:checked').map(function(){
              return $(this).val();
          }).get();
          var timeTaken = $('#timer').text();
          $.ajax({
            method: 'POST',
            url: "#{answers_path}" + '?question_id=' + questionId + '&answers=' + answers + '&time_taken=' + timeTaken,
            dataType: 'script',
          });
          nextStepWizard.removeAttr('disabled').trigger('click');
        }
        var currentId = $(this).parents('.setup-content').attr('id');
        var lastWID = $('.stepwizard form').children('.setup-content:last').attr('id');
        if (lastWID == currentId) {
          $('#timer').hide();
          $.ajax({
            method: 'GET',
            url: "#{close_tests_path}",
            dataType: 'script'
          });
        }
    });

    $('div.setup-panel div a.btn-primary').trigger('click');
    $('.stepwizard').find('.setup-content').each(function(){
      if ($(this).is(':visible')) {
        var setupCont = $(this);
        var mins = setupCont.find('.question-tag .question-time').val()/60;
        var date = new  Date();
        date.setMinutes(date.getMinutes() + mins);
        $("#timer")
          .countdown(date, function(event) {
            $(this).text(
              event.strftime('%M:%S')
            );
        }).on('finish.countdown', function(){
          setupCont.find('.nextBtn').click();
        });
      }
    });

    $('#timer').click(function(e){
      e.preventDefault();
    });
  });

app/views/shared/_errors.html.haml
- errors.map do |error|
  %li
    = error.to_s

app/views/shared/_generic.html.haml
#generic_modal{ :class => "modal fade", :role => "for forms", style: 'z-index: 2000;' }
  %div{ :class => "modal-dialog" }
    %div{ :class => "modal-content" }
      %div{ :class => "modal-header" }
        %button{ :type => "button", :class => "close", 'data-dismiss' => "modal", 'aria-label' => "Close" }
          %span{ 'aria-hidden' => "true" }
            &times;
        %h4{ :class => "modal-title" }
      %div{ :class => "modal-body" }
        %ul#error
        .row
          .col-md-12
            #content

app/views/shared/_thankyou_form.html.haml
#generic_modal{ :class => "modal fade", :role => "for forms" }
  %div{ :class => "modal-dialog" }
    %div{ :class => "modal-content" }
      %div{ :class => "modal-header" }
        %button{ :type => "button", :class => "close", 'data-dismiss' => "modal", 'aria-label' => "Close" }
          %span{ 'aria-hidden' => "true" }
            &times;
        %h4{ :class => "modal-title" }
      %div{ :class => "modal-body" }
        %ul#error
        .row
          .col-md-12
            #content{ style: 'display: flex;flex-direction:column;align-items: center;justification-content: center;' }
              %a.btn.btn-default.btn1{ "data-dismiss": "modal" }
                CLOSE

app/views/users/_score_card.html.haml
.score-card-container
  .user-details
    .row
      .col-md-12
        .col-md-6
          %p
            %span
              %label
                = "Name : "
              = @user.name
          %p
            %span
              %label
                = "Email : "
              = @user.email
          %p
            %span
              %label
                = "Contact : "
              = @user.phone_number
        .col-md-6
          %p
            %span
              %label
                = "No of questions : "
              = @questions.size
          %p
            %span
              %label
                = "Attempted questions : "
              = @user_attempted_questions.size
          %p
            %span
              %label
                = "Total score : "
              = @correct_ans

app/views/users/create.js.erb
<% if @user.errors.present? %>
  $('.user-container .error-content').html("<%= j render 'shared/errors', errors: @user.errors.full_messages %>");
<% else %>
  $(window.location.replace("<%= questions_path %>"));
<% end %>

app/views/users/details.html.haml
.user-details-container
  .row
    .col-md-12.header-content
      .col-md-3
        Name
      .col-md-3
        Email
      .col-md-3
        Contact
      .col-md-3
        View Score
  - if @users.present?
    - @users.each do |user|
      .row
        .col-md-12.body-content
          .col-md-3
            = user.name
          .col-md-3
            = user.email
          .col-md-3
            = user.phone_number
          .col-md-3
            %a{ href: score_user_path(user.id) }
              Score
  - else
    .row
      .col-md-12.empty-questions-content
        **********Users Not Attempted!!!**********

= render 'shared/generic'

app/views/users/index.html.haml
.user-container
  .row
    .col-md-12
      .col-md-4.col-sm-3.col-xs-2
      .col-md-4.col-sm-6.col-xs-8.user-form
        .user-form-container
          .error-content
          %div
            %h4
              = t('provide_details')
          = form_tag("#{users_path}", method: 'POST', remote: true) do
            .row
              .col-md-12
                %label
                  = t('name')
                %input.form-control{ type: 'text', name: 'name' }
            .row
              .col-md-12
                %label
                  = t('email')
                %input.form-control{ type: 'text', name: 'email' }
            .row
              .col-md-12
                %label
                  = t('phone_number')
                %input.form-control{ type: 'text', name: 'phone_number' }
            .row
              .col-md-12.btn-actions
                %button.btn.btn-default{ type: 'submit' }
                  = t('submit')
      .col-md-4.col-sm-3.col-xs-2

app/views/users/score.html.haml
.score-card-container
  .row
    .col-md-12
      %h4
        Score Details
  .row
    .col-md-12
      .col-md-6
        %p
          %span
            %label
              = "Name : "
            = @user.name
          %p
            %span
              %label
                = "Email : "
              = @user.email
          %p
            %span
              %label
                = "Contact : "
              = @user.phone_number
      .col-md-6
        %p
          %span
            %label
              = "No of questions : "
            = @questions.size
          %p
            %span
              %label
                = "Attempted questions : "
              = @user_attempted_questions.size
          %p
            %span
              %label
                = "Total score : "
              = @correct_ans
  .row
    .col-md-12
      %h4
        Questions
  - @questions.each do |question|
    - qns_ans = question.answer_ids.map { |x| x.to_s }
    - user_qns = @user_attempted_questions.pluck(:question_id)
    - if user_qns.include? question.id
      - user_ans = @user_attempted_questions.where(question_id: question.id).first
      - user_ans_ids = user_ans.answer_ids
      - ans = user_ans_ids.map { |ans_id| qns_ans.include? ans_id }
      - if ans.all? { |ele| ele }
        .row
          .col-md-12
            .user-qn-content.green
              %div
                = "Q : #{question.content}"
              .timer-content
                = Time.at(user_ans.time_taken).utc.strftime("%M:%S")

      - else
        .row
          .col-md-12
            .user-qn-content.red
              %div
                = "Q : #{question.content}"
              .timer-content
                = Time.at(user_ans.time_taken).utc.strftime("%M:%S")
    - else
      .row
        .col-md-12
          .user-qn-content.dull
            %div
              = "Q : #{question.content}"

app/views/users/score.js.erb
$('#generic_modal .modal-body #content').html("<%= j render 'users/score_card' %>");
showModel("User Score", false);